### ISSUE TITLE
No Organization error

### ISSUE THREAD

**Issue by damico** [JohnDeere/MyJohnDeereAPI-OAuth-Java-Client#22]
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
> 	at java.util.ArrayList.get(ArrayList.java:433)
> 	at com.deere.democlient.apis.Partnerships.getUserOrganizations(Partnerships.java:69)
> 	at com.deere.democlient.apis.Partnerships.main(Partnerships.java:31)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
> 	at java.lang.Thread.run(Thread.java:748)

When you run `$ mvn exec:java -Dexec.mainClass="com.deere.democlient.apis.Partnerships"` but you did not add an organization in operation center, the call to endpoint https://sandboxapi.deere.com/platform/users/josedamico/organizations will return:
 ```js
{"links":[{"rel":"self","uri":"https://sandboxapi.deere.com/platform/users/josedamico/organizations"}],"total":0,"values":[]}
```

**Comment by tpravin** [comment]
Thanks for the feedback, we will take care of it.
